### ISSUE TITLE
Getting error when run "mvn clean install -PautoInstallSinglePackage -Pclassic" 

### ISSUE THREAD

**Issue by DengChen0412** [AdobeDocs/experience-manager-learn.en#107]
Issue in ./help/spa-angular-tutorial/integrate-spa.md

I got an error in this step [Deploy SPA updates to AEM](https://experienceleague.adobe.com/docs/experience-manager-learn/spa-angular-tutorial/integrate-spa.html?lang=en#deploy-spa-updates-to-aem).
It seems failed at "ng test" after I followed the steps above.

Can any body help me please??? 

```
\aem-guides-wknd-spa> mvn clean install -PautoInstallSinglePackage -Pclassic
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] wknd-spa-angular                                                   [pom]
[INFO] WKND SPA Angular - Core                                            [jar]
[INFO] wknd-spa-angular.ui.frontend - UI Frontend                         [pom]
[INFO] WKND SPA Angular - Repository Structure Package        [content-package]
[INFO] WKND SPA Angular - UI apps                             [content-package]
[INFO] WKND SPA Angular - UI content                          [content-package]
[INFO] WKND SPA Angular - All                                 [content-package]
[INFO] WKND SPA Angular - Integration Tests                               [jar]
[INFO] WKND SPA Angular - Dispatcher                                      [pom]
[INFO]
[INFO] ---------------< com.adobe.aem.guides:wknd-spa-angular >----------------
[INFO] Building wknd-spa-angular 1.0.0-SNAPSHOT                           [1/9]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO]
[INFO] --- maven-clean-plugin:3.0.0:clean (default-clean) @ wknd-spa-angular ---
[INFO]
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce-maven) @ wknd-spa-angular ---
[INFO]
[INFO] --- maven-install-plugin:2.5.2:install (default-install) @ wknd-spa-angular ---
[INFO] Installing C:\Users\XXXXXXX\Documents\Git\spa demo\aem-guides-wknd-spa\pom.xml to C:\Users\XXXXXXX\.m2\repository\com\adobe\aem\guides\wknd-spa-angular\1.0.0-SNAPSHOT\wknd-spa-angular-1.0.0-SNAPSHOT.pom
[INFO]
[INFO] -------------< com.adobe.aem.guides:wknd-spa-angular.core >-------------
[INFO] Building WKND SPA Angular - Core 1.0.0-SNAPSHOT                    [2/9]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-clean-plugin:3.0.0:clean (default-clean) @ wknd-spa-angular.core ---
[INFO] Deleting C:\Users\XXXXXXX\Documents\Git\spa demo\aem-guides-wknd-spa\core\target
[INFO]
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce-maven) @ wknd-spa-angular.core ---
[INFO]
[INFO] --- maven-resources-plugin:3.0.2:resources (default-resources) @ wknd-spa-angular.core ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\Users\XXXXXXX\Documents\Git\spa demo\aem-guides-wknd-spa\core\src\main\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ wknd-spa-angular.core ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 10 source files to C:\Users\XXXXXXX\Documents\Git\spa demo\aem-guides-wknd-spa\core\target\classes
[INFO]
[INFO] --- bnd-maven-plugin:5.0.0:bnd-process (bnd-process) @ wknd-spa-angular.core ---
[WARNING] C:\Users\XXXXXXX\Documents\Git\spa demo\aem-guides-wknd-spa\core\pom.xml [0:0]: No translation found for macro: componentGroupName
[INFO]
[INFO] --- maven-resources-plugin:3.0.2:testResources (default-testResources) @ wknd-spa-angular.core ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\Users\XXXXXXX\Documents\Git\spa demo\aem-guides-wknd-spa\core\src\test\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ wknd-spa-angular.core ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 5 source files to C:\Users\XXXXXXX\Documents\Git\spa demo\aem-guides-wknd-spa\core\target\test-classes
[INFO]
[INFO] --- maven-surefire-plugin:2.22.1:test (default-test) @ wknd-spa-angular.core ---
[INFO]
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running com.adobe.aem.guides.wknd.spa.angular.core.filters.LoggingFilterTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.444 s - in com.adobe.aem.guides.wknd.spa.angular.core.filters.LoggingFilterTest
[INFO] Running com.adobe.aem.guides.wknd.spa.angular.core.listeners.SimpleResourceListenerTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.006 s - in com.adobe.aem.guides.wknd.spa.angular.core.listeners.SimpleResourceListenerTest
[INFO] Running com.adobe.aem.guides.wknd.spa.angular.core.models.HelloWorldModelTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.019 s - in com.adobe.aem.guides.wknd.spa.angular.core.models.HelloWorldModelTest
[INFO] Running com.adobe.aem.guides.wknd.spa.angular.core.schedulers.SimpleScheduledTaskTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.025 s - in com.adobe.aem.guides.wknd.spa.angular.core.schedulers.SimpleScheduledTaskTest
[INFO] Running com.adobe.aem.guides.wknd.spa.angular.core.servlets.SimpleServletTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.043 s - in com.adobe.aem.guides.wknd.spa.angular.core.servlets.SimpleServletTest
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[INFO]
[INFO] --- maven-jar-plugin:3.1.2:jar (default-jar) @ wknd-spa-angular.core ---
[INFO] Building jar: C:\Users\XXXXXXX\Documents\Git\spa demo\aem-guides-wknd-spa\core\target\wknd-spa-angular.core-1.0.0-SNAPSHOT.jar
[INFO]
[INFO] --- bnd-baseline-maven-plugin:5.0.0:baseline (baseline) @ wknd-spa-angular.core ---
[INFO] Determining the baseline version for com.adobe.aem.guides:wknd-spa-angular.core:jar:(,1.0.0-SNAPSHOT) using repositories [adobe-public-releases (https://repo.adobe.com/nexus/content/groups/public, default, releases), adobe-aem-releases (https://downloads.experiencecloud.adobe.com/content/maven/public, default, releases), central (https://repo.maven.apache.org/maven2, default, releases)]
[INFO] The baseline version was found to be null
[WARNING] No previous version of com.adobe.aem.guides:wknd-spa-angular.core:jar:1.0.0-SNAPSHOT could be found to baseline against
[INFO]
[INFO] --- maven-install-plugin:2.5.2:install (default-install) @ wknd-spa-angular.core ---
[INFO] Installing C:\Users\XXXXXXX\Documents\Git\spa demo\aem-guides-wknd-spa\core\target\wknd-spa-angular.core-1.0.0-SNAPSHOT.jar to C:\Users\XXXXXXX\.m2\repository\com\adobe\aem\guides\wknd-spa-angular.core\1.0.0-SNAPSHOT\wknd-spa-angular.core-1.0.0-SNAPSHOT.jar
[INFO] Installing C:\Users\XXXXXXX\Documents\Git\spa demo\aem-guides-wknd-spa\core\pom.xml to C:\Users\XXXXXXX\.m2\repository\com\adobe\aem\guides\wknd-spa-angular.core\1.0.0-SNAPSHOT\wknd-spa-angular.core-1.0.0-SNAPSHOT.pom
[INFO]
[INFO] ---------< com.adobe.aem.guides:wknd-spa-angular.ui.frontend >----------
[INFO] Building wknd-spa-angular.ui.frontend - UI Frontend 1.0.0-SNAPSHOT [3/9]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO]
[INFO] --- maven-clean-plugin:3.0.0:clean (default-clean) @ wknd-spa-angular.ui.frontend ---
[INFO]
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce-maven) @ wknd-spa-angular.ui.frontend ---
[INFO]
[INFO] --- frontend-maven-plugin:1.7.6:install-node-and-npm (install node and npm) @ wknd-spa-angular.ui.frontend ---
[INFO] Node v13.7.0 is already installed.
[INFO] NPM 6.13.0 is already installed.
[INFO]
[INFO] --- frontend-maven-plugin:1.7.6:npm (npm install) @ wknd-spa-angular.ui.frontend ---
[INFO] Running 'npm install' in C:\Users\XXXXXXX\Documents\Git\spa demo\aem-guides-wknd-spa\ui.frontend
[WARNING] npm WARN @adobe/cq-angular-editable-components@2.0.2 requires a peer of @adobe/cq-spa-component-mapping@~1.0.3 but none is installed. You must install peer dependencies yourself.
[WARNING] npm WARN @adobe/cq-angular-editable-components@2.0.2 requires a peer of @adobe/cq-spa-page-model-manager@~1.0.7 but none is installed. You must install peer dependencies yourself.
[WARNING] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules\fsevents):
[WARNING] npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
[WARNING] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.1 (node_modules\chokidar\node_modules\fsevents):
[WARNING] npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
[WARNING] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\karma\node_modules\fsevents):
[WARNING] npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
[WARNING] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\webpack-dev-server\node_modules\fsevents):
[WARNING] npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
[WARNING] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\watchpack-chokidar2\node_modules\fsevents):
[WARNING] npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
[ERROR]
[INFO] audited 1484 packages in 5.581s
[INFO]
[INFO] 47 packages are looking for funding.
[INFO] Run "npm fund" to find out more.
[INFO]
[INFO] --- frontend-maven-plugin:1.7.6:npm (npm run test) @ wknd-spa-angular.ui.frontend ---
[INFO] Running 'npm test' in C:\Users\XXXXXXX\Documents\Git\spa demo\aem-guides-wknd-spa\ui.frontend
[INFO]
[INFO] > wknd-spa-angular@0.1.0 test C:\Users\XXXXXXX\Documents\Git\spa demo\aem-guides-wknd-spa\ui.frontend
[INFO] > ng test
[INFO]
[ERROR] (node:36604) ExperimentalWarning: Conditional exports is an experimental feature. This feature could change at any time
[ERROR] Error: UNKNOWN: unknown error, scandir 'C:/Users/XXXXXXX/OneDrive - XXXXX/Documents/Git/spa demo/aem-guides-wknd-spa/ui.frontend/node_modules/colors/themes'
[ERROR]     at Object.readdirSync (fs.js:887:3)
[ERROR]     at NodeJSFileSystem.readdir (C:\Users\XXXXXXX\Documents\Git\spa demo\aem-guides-wknd-spa\ui.frontend\node_modules\@angular\compiler-cli\src\ngtsc\file_system\src\node_js_file_system.js:52:23)
[ERROR]     at _loop_1 (C:\Users\XXXXXXX\Documents\Git\spa demo\aem-guides-wknd-spa\ui.frontend\node_modules\@angular\compiler-cli\ngcc\src\entry_point_finder\directory_walker_entry_point_finder.js:164:44)
[ERROR]     at DirectoryWalkerEntryPointFinder.collectSecondaryEntryPoints (C:\Users\XXXXXXX\Documents\Git\spa demo\aem-guides-wknd-spa\ui.frontend\node_modules\@angular\compiler-cli\ngcc\src\entry_point_finder\directory_walker_entry_point_finder.js:176:21)
[INFO] 22 01 2021 13:06:59.693:ERROR [karma-server]: Server start failed on port 9876: Error: NGCC failed.
[ERROR]     at DirectoryWalkerEntryPointFinder.walkDirectoryForPackages (C:\Users\XXXXXXX\Documents\Git\spa demo\aem-guides-wknd-spa\ui.frontend\node_modules\@angular\compiler-cli\ngcc\src\entry_point_finder\directory_walker_entry_point_finder.js:88:22)
[ERROR]     at DirectoryWalkerEntryPointFinder.walkDirectoryForPackages (C:\Users\XXXXXXX\Documents\Git\spa demo\aem-guides-wknd-spa\ui.frontend\node_modules\@angular\compiler-cli\ngcc\src\entry_point_finder\directory_walker_entry_point_finder.js:114:79)
[ERROR]     at C:\Users\XXXXXXX\Documents\Git\spa demo\aem-guides-wknd-spa\ui.frontend\node_modules\@angular\compiler-cli\ngcc\src\entry_point_finder\directory_walker_entry_point_finder.js:64:80
[ERROR]     at Object.trackDuration (C:\Users\XXXXXXX\Documents\Git\spa demo\aem-guides-wknd-spa\ui.frontend\node_modules\@angular\compiler-cli\ngcc\src\entry_point_finder\utils.js:92:22)
[ERROR]     at DirectoryWalkerEntryPointFinder.walkBasePathForPackages (C:\Users\XXXXXXX\Documents\Git\spa demo\aem-guides-wknd-spa\ui.frontend\node_modules\@angular\compiler-cli\ngcc\src\entry_point_finder\directory_walker_entry_point_finder.js:64:39)
[ERROR]     at DirectoryWalkerEntryPointFinder.findEntryPoints (C:\Users\XXXXXXX\Documents\Git\spa demo\aem-guides-wknd-spa\ui.frontend\node_modules\@angular\compiler-cli\ngcc\src\entry_point_finder\directory_walker_entry_point_finder.js:42:30)
[ERROR] Error: NGCC failed.
[ERROR]     at NgccProcessor.process (C:\Users\XXXXXXX\Documents\Git\spa demo\aem-guides-wknd-spa\ui.frontend\node_modules\@ngtools\webpack\src\ngcc_processor.js:76:19)
[ERROR]     at C:\Users\XXXXXXX\Documents\Git\spa demo\aem-guides-wknd-spa\ui.frontend\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:579:31
[ERROR]     at SyncHook.eval (eval at create (C:\Users\XXXXXXX\Documents\Git\spa demo\aem-guides-wknd-spa\ui.frontend\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:7:1)
[ERROR]     at SyncHook.lazyCompileHook (C:\Users\XXXXXXX\Documents\Git\spa demo\aem-guides-wknd-spa\ui.frontend\node_modules\tapable\lib\Hook.js:154:20)
[ERROR]     at webpack (C:\Users\XXXXXXX\Documents\Git\spa demo\aem-guides-wknd-spa\ui.frontend\node_modules\webpack\lib\webpack.js:55:30)
[ERROR]     at init (C:\Users\XXXXXXX\Documents\Git\spa demo\aem-guides-wknd-spa\ui.frontend\node_modules\@angular-devkit\build-angular\src\angular-cli-files\plugins\karma.js:130:20)
[ERROR]     at Array.invoke (C:\Users\XXXXXXX\Documents\Git\spa demo\aem-guides-wknd-spa\ui.frontend\node_modules\di\lib\injector.js:75:15)
[ERROR]     at Injector.get (C:\Users\XXXXXXX\Documents\Git\spa demo\aem-guides-wknd-spa\ui.frontend\node_modules\di\lib\injector.js:48:43)
[ERROR]     at C:\Users\XXXXXXX\Documents\Git\spa demo\aem-guides-wknd-spa\ui.frontend\node_modules\karma\lib\server.js:153:61
[ERROR]     at Array.forEach (<anonymous>)
[ERROR]     at Server._start (C:\Users\XXXXXXX\Documents\Git\spa demo\aem-guides-wknd-spa\ui.frontend\node_modules\karma\lib\server.js:153:23)
[ERROR]     at Injector.invoke (C:\Users\XXXXXXX\Documents\Git\spa demo\aem-guides-wknd-spa\ui.frontend\node_modules\di\lib\injector.js:75:15)
[ERROR]     at Server.start (C:\Users\XXXXXXX\Documents\Git\spa demo\aem-guides-wknd-spa\ui.frontend\node_modules\karma\lib\server.js:127:22)
[ERROR] npm ERR! Test failed.  See above for more details.
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for wknd-spa-angular 1.0.0-SNAPSHOT:
[INFO]
[INFO] wknd-spa-angular ................................... SUCCESS [  0.403 s]
[INFO] WKND SPA Angular - Core ............................ SUCCESS [  6.816 s]
[INFO] wknd-spa-angular.ui.frontend - UI Frontend ......... FAILURE [ 16.135 s]
[INFO] WKND SPA Angular - Repository Structure Package .... SKIPPED
[INFO] WKND SPA Angular - UI apps ......................... SKIPPED
[INFO] WKND SPA Angular - UI content ...................... SKIPPED
[INFO] WKND SPA Angular - All ............................. SKIPPED
[INFO] WKND SPA Angular - Integration Tests ............... SKIPPED
[INFO] WKND SPA Angular - Dispatcher ...................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  24.828 s
[INFO] Finished at: 2021-01-22T13:06:59+09:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.7.6:npm (npm run test) on project wknd-spa-angular.ui.frontend: Failed to run task: 'npm test' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :wknd-spa-angular.ui.frontend
```

**Comment by godanny86** [comment]
@DengChen0412 did you get this error when you initially build the chapter starter code at the start of the chapter? 

I'm not sure, but I noticed that the folder structure you have includes spaces in the folder names. Can you try moving the project to a folder structure with no spaces in the name?

**Comment by DengChen0412** [comment]
Thank you very much for your responding.
I didn't got the same error when I initially build the starter code.
I changed deleted the space in the folder names, but nothing changes.

And I have tried to delete aem-guides-wknd-spa folder and git clone your codes again, It runs fine with the initially build.
But "mvn clean install -PautoInstallSinglePackage -Pclassic" will fail again after I made some changes to the codes in ui.frontend...

**Comment by godanny86** [comment]
Are you able to checkout and build the solution branch? https://github.com/adobe/aem-guides-wknd-spa/tree/Angular/integrate-spa-solution

**Comment by DengChen0412** [comment]
Checkouting didn't help me, so I deleted the folder and did git clone again, then it worked for me! Thank you very much!!!

But the style for header (header.component.scss) seems hasn't applied to my AEM 6.5.

My sites editor view:
( http://localhost:4502/editor.html/content/wknd-spa-angular/us/en/home.html )
![image](https://user-images.githubusercontent.com/57550059/105453753-10322800-5cc4-11eb-93df-a4c0b1f84d0c.png)

And when I run "npm run start:mock":
( http://localhost:4200/content/wknd-spa-angular/us/en/home.html )
![image](https://user-images.githubusercontent.com/57550059/105453827-38218b80-5cc4-11eb-9c83-68e6d4db02bb.png)

**Comment by godanny86** [comment]
Hmm, I'm not sure. Perhaps a browser cache issue? Can you inspect that the css under clientlib-angular under `/apps` got updated? You can view it in CRXDE lite as well...

**Comment by DengChen0412** [comment]
Thank you again for your responding!
It's my fault, the directory I run mvn was under ui.frontend.
It's now resolved !

**Comment by godanny86** [comment]
Great to hear @DengChen0412 !
