### ISSUE TITLE
SetValueApp.core-1.0-SNAPSHOT.jar linked in Adaptive Form Articles

### ISSUE THREAD

**Issue by aemarch** [AdobeDocs/experience-manager-learn.en#15]
Issue in help/forms/adaptive-forms/setvalue-aem-forms-workflow-tutorial-use.md

The SetValue Custom OSGI Bundle (SetValueApp.core-1.0-SNAPSHOT.jar) provided in various adaptive form/workflow articles throws an error on install:

Log:
*ERROR* [qtp1509491925-4255] org.apache.felix.http.jetty Exception while processing request to /system/console/bundles (java.io.IOException: Bundle-SymbolicName header missing, cannot install bundle)
java.io.IOException: Bundle-SymbolicName header missing, cannot install bundle
org.apache.felix.webconsole.internal.core.BundlesServlet.installBundle(BundlesServlet.java:1630) [org.apache.felix.webconsole:4.3.12]
        at org.apache.felix.webconsole.internal.core.BundlesServlet.installBundles(BundlesS

When I tried extracting files from the jar, I got the following:

jar xvf SetValueApp.core-1.0-SNAPSHOT.jar
java.util.zip.ZipException: invalid code lengths set
	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:164)
	at java.util.zip.ZipInputStream.read(ZipInputStream.java:194)
	at java.util.zip.ZipInputStream.closeEntry(ZipInputStream.java:140)
	at java.util.zip.ZipInputStream.getNextEntry(ZipInputStream.java:118)
	at sun.tools.jar.Main.extract(Main.java:979)
	at sun.tools.jar.Main.run(Main.java:311)
	at sun.tools.jar.Main.main(Main.java:1288)

**Comment by girishadobe** [comment]
I have updated the bundle. Can you please try now and let me know if that works

**Comment by godanny86** [comment]
closing this due to inactivity.
