### ISSUE TITLE
[AEM Forms] Error GetWidgetUrl.doPost

### ISSUE THREAD

**Issue by vidhyabhushanbahl** [AdobeDocs/experience-manager-learn.en#152]
Issue in ./help/forms/react-ic-sign/deploy-assets-on-your-server.md

Can we have source code ? I have deployed the code on AEM v6.5 and it failing with 

```
2.06.2023 12:55:14.739 *ERROR* [[0:0:0:0:0:0:0:1] [1687418714735] POST /bin/getwidgeturl HTTP/1.1] org.apache.sling.engine.impl.SlingRequestProcessorImpl service: Uncaught Throwable
java.lang.NoSuchMethodError: com.google.gson.JsonParser.parseString(Ljava/lang/String;)Lcom/google/gson/JsonElement;
	at com.acrobatsign.core.servlets.GetWidgetUrl.doPost(GetWidgetUrl.java:36) [AcrobatSign.core:1.0.0.SNAPSHOT]
	at org.apache.sling.api.servlets.SlingAllMethodsServlet.mayService(SlingAllMethodsServlet.java:146) [org.apache.sling.api:2.22.0]
	at org.apache.sling.api.servlets.SlingSafeMethodsServlet.service(SlingSafeMethodsServlet.java:342) [org.apache.sling.api:2.22.0]
	at org.apache.sling.api.servlets.SlingSafeMethodsServlet.service(SlingSafeMethodsServlet.java:374) [org.apache.sling.api:2.22.0]
	at org.apache.sling.engine.impl.request.RequestData.service(RequestData.java:574) [org.apache.sling.engine:2.7.8]
```

**Comment by gbedekar** [comment]
are all your bundles active? you can also decompile the jar  to get the source code
