### ISSUE TITLE
Can't synchronise core bundle with AEM instance

### ISSUE THREAD

**Issue by FFerreira84** [AdobeDocs/experience-manager-learn.en#64]
Issue in help/getting-started-wknd-tutorial-develop/component-basics.md

I'm running into an issue where, while following the Component Basics tutorial, when I try to add the core bundle to be synchronised with the AEM instance in Eclipse (after adding ui.apps and ui.content), I get an error:

"Failed installing bundle : Dir /Users/username/code/component-basics/aem-guides-wknd/core/target/classes does not exist"

That directory does exist, I've tried deleting the entire project and starting over again, I didn't spot any errors from maven at any point. Any ideas on what could be going wrong?

**Comment by FFerreira84** [comment]
Just noticed that the error occurs even before trying to add the module to be synchronised. When I refresh this project, four errors pop up in the eclipse error log, they're all the same:

eclipse.buildId=4.16.0.I20200604-0540
java.version=1.8.0_251
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_GB
Framework arguments:  -product org.eclipse.epp.package.jee.product -product org.eclipse.epp.package.jee.product -product org.eclipse.epp.package.jee.product
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -product org.eclipse.epp.package.jee.product -product org.eclipse.epp.package.jee.product -data file:/Users/username/eclipse-workspace/ -product org.eclipse.epp.package.jee.product

org.apache.sling.ide.eclipse-core
Error
Fri Jul 03 17:56:43 BST 2020
Failed installing bundle : Dir /Users/username/code/component-basics/aem-guides-wknd/core/target/classes does not exist

org.apache.sling.ide.osgi.OsgiClientException: Dir /Users/username/code/component-basics/aem-guides-wknd/core/target/classes does not exist
	at org.apache.sling.ide.osgi.impl.HttpOsgiClient$LocalBundleInstaller.installBundle(HttpOsgiClient.java:334)
	at org.apache.sling.ide.osgi.impl.HttpOsgiClient.installLocalBundle(HttpOsgiClient.java:196)
	at org.apache.sling.ide.osgi.impl.TracingOsgiClient.logInstallLocalBundle(TracingOsgiClient.java:77)
	at org.apache.sling.ide.osgi.impl.TracingOsgiClient.installLocalBundle(TracingOsgiClient.java:59)
	at org.apache.sling.ide.eclipse.core.internal.SlingLaunchpadBehaviour.publishBundleModule(SlingLaunchpadBehaviour.java:357)
	at org.apache.sling.ide.eclipse.core.internal.SlingLaunchpadBehaviour.publishModule(SlingLaunchpadBehaviour.java:234)
	at org.eclipse.wst.server.core.model.ServerBehaviourDelegate.publishModule(ServerBehaviourDelegate.java:1093)
	at org.eclipse.wst.server.core.model.ServerBehaviourDelegate.publishModules(ServerBehaviourDelegate.java:1185)
	at org.apache.sling.ide.eclipse.core.internal.ServerBehaviourDelegateWithModulePublishSupport.publish(ServerBehaviourDelegateWithModulePublishSupport.java:137)
	at org.eclipse.wst.server.core.model.ServerBehaviourDelegate.publish(ServerBehaviourDelegate.java:776)
	at org.apache.sling.ide.eclipse.core.internal.ServerBehaviourDelegateWithModulePublishSupport.publish(ServerBehaviourDelegateWithModulePublishSupport.java:54)
	at org.eclipse.wst.server.core.internal.Server.publishImpl(Server.java:3184)
	at org.eclipse.wst.server.core.internal.Server$PublishJob.run(Server.java:357)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
